version: '3'
services: 
    mynoetic:
        #image: osrf/ros:melodic-desktop-full
        build:
            context: .
        container_name: mynoetic
        environment: 
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          - "TERM=xterm-256color" 
        volumes: 
          - "/home/$USER:/home/HOST"
          - "/etc/sudoers.d:/etc/sudoers.d:ro"
          - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        #devices: 
        #- "/dev/ttyUSB0:/dev/ttyUSB0"
        tty: true
        stdin_open: true
